### PR TITLE
MEPTS-406: change on the base cohort

### PR DESCRIPTION
**Pull request by psmatsinhe**

### CODE REVIEW

**Comment by ningosi** [comment]
Looks like the base cohort is NOT well mapped in this class SetupUSMonthlySummaryHivReport

**Comment by ningosi** [comment]
@psmatsinhe are you suppossed to map here or is a different case https://github.com/esaude/openmrs-module-eptsreports/blob/MEPTS-406/api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupUSMonthlySummaryHivReport.java#L53

**Comment by ningosi** [comment]
getting this error **[ERROR] /home/codehub/workspace/openmrs-module-eptsreports/api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupUSMonthlySummaryHivReport.java:[57,65] '(' or '[' expected** when I try building the branch

**Comment by ningosi** [comment]
Also looks like there other files changed that are NOT supposed to

**Comment by psmatsinhe** [comment]
> @psmatsinhe are you suppossed to map here or is a different case https://github.com/esaude/openmrs-module-eptsreports/blob/MEPTS-406/api/src/main/java/org/openmrs/module/eptsreports/reporting/reports/SetupUSMonthlySummaryHivReport.java#L53

Hi @ningosi, that is supposed to be changed but I dont think this report is being used anymore...

**Comment by ningosi** [comment]
Tests failing. Please correct those

**Pull request merged**
