### PR TITLE
MEPTS-157: Review & test TxNew and TxCurr

### PR DESCRIPTION
**Pull request by ynurmahomed**
This will enable us to consider patients wrongly registered with age > 200.
Use current year to be safe, bigger values might cause problems
with AgeCohortDefinition.

This solution needs to be revised.

### CODE REVIEW

**Comment by ynurmahomed** [comment]
I have also updated the template for TX_CURR report

**Comment by nthfloor** [comment]
Lets leave this for now - the scenario of patients older than 200 is an anomaly which should not happen in real life. But we need a more permanent solution for this which can form a tech debt ticket for next week.

**Comment by nthfloor** [comment]
@ynurmahomed what did you update for TxCurr? Can you please commit that change to [this PR](https://github.com/esaude/openmrs-module-eptsreports/pull/74) since we are not going to merge this change for txNew.

**Comment by ynurmahomed** [comment]
@nthfloor there were no changes for TX_CURR

**Pull request closed without merging**
