### PR TITLE
MEPTS-101: Refactor retention queries

### PR DESCRIPTION
**Pull request by edrisse**

### CODE REVIEW

**Comment by Guimino** [comment]
@edrisse , I found differences running **PEPFAR_MER_2.3** report on FGH db for the indicator **TX_NEW**,  desagregation **<1 Male**

**Comment by edrisse** [comment]
> @edrisse , I found differences running **PEPFAR_MER_2.3** report on FGH db for the indicator **TX_NEW**, desagregation **<1 Male**

The differing patient was admitted on ART before he was born. We ignore those on the new code.

**Comment by edrisse** [comment]
> @edrisse , I found differences running **PEPFAR_MER_2.3** report on FGH db for the indicator **TX_NEW**, desagregation **<1 Male**

Fixed @Guimino, please test again. I included a test results spreadsheet at https://docs.google.com/spreadsheets/d/1myfOxWbj_-zazk21VN_FdaIAE94vFcrxC9un1CjrwdE/edit#gid=9297815 you can add your test data there

**Comment by Guimino** [comment]
@edrisse , well done, **PEPFAR_MER_2.3** is now matching, however, there are some differences in  Early Retention 4 months ,  column desagregations are: _Initiated ART_, _Alive & Not transferred out and Defaulter_, _Lost To Follow-Up_
report result is available on https://docs.google.com/spreadsheets/d/1diHJa22qDOjgfnQU6w3CpgkJBhMCXSfciqqWLZ80YR8/edit#gid=201090711

**Comment by edrisse** [comment]
Fixed @Guimino , affects PEPFAR 2.3 report as well

**Pull request merged**
