### PR TITLE
Mepts 77 update txcurr composition

### PR DESCRIPTION
**Pull request by nthfloor**
We are updating the TxCurr composition string as defined in this user [story](https://docs.google.com/document/d/1e0YmjOlv8WyFg7C8rYPBqaZ8tqke8GJihKMQkXrrAUQ/edit?ts=5c3d7f5f)

### CODE REVIEW

**Comment by nthfloor** [comment]
Thanks Yassin :+1: , please upload the compiled version of this PR to QA for Pinki to test.

**Comment by ningosi** [comment]
@nthfloor and @ynurmahomed we need to intersect the resultant composition string with base cohort

**Comment by nthfloor** [comment]
@ningosi the composition is already intersected with the base cohort [here](https://github.com/esaude/openmrs-module-eptsreports/blob/3b29e0921dd6c0d61d5af19aa49877303415fff4/api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxCurrCohortQueries.java#L345)

**Comment by Guimino** [comment]
the composition string reflects what is specified, I put  as ordered in the spec and  the result is the same as @nthfloor 
(1 OR 2 OR 3 OR 4) AND NOT (11 AND 6) AND NOT (NOT 11 AND 12 AND 7) AND NOT 5

**Pull request merged**
