### PR TITLE
MEPTS-307: RTT changes

### PR DESCRIPTION
**Pull request by nthfloor**

### CODE REVIEW

**Review by ynurmahomed — COMMENTED** [review]
Changes look good.

But, it seems that none of the other methods except for `getAllPatientsWhoDelayedMoreThan28Days` are necessary.

I think its better to leave just that one.

**Comment by nthfloor** [comment]
Thanks @ynurmahomed, so I did try and remove all other unused methods - perhaps I missed some.

What other methods do you still see?

**Comment by ynurmahomed** [comment]
I was referring to `getAllPatientsWhoMissedAppointmentBy28Or30DaysButLaterHadVisit`, does not need to be a composition anymore.
We could do this:
```
public CohortDefinition getAllPatientsWhoMissedAppointmentBy28Or30DaysButLaterHadVisit() {
    return getAllPatientsWhoDelayedMoreThan28Days();
}
```
Then maybe inline `getAllPatientsWhoDelayedMoreThan28Days` :
```
public CohortDefinition getAllPatientsWhoMissedAppointmentBy28Or30DaysButLaterHadVisit() {
    return genericCohortQueries.generalSql(
        "Having visit 30 days later",
        TxRttQueries.getAllPatientsWhoMissedPreviousAppointmentBy28Days(
            hivMetadata.getAdultoSeguimentoEncounterType().getEncounterTypeId(),
            hivMetadata.getARVPediatriaSeguimentoEncounterType().getEncounterTypeId(),
            hivMetadata.getARVPharmaciaEncounterType().getEncounterTypeId(),
            hivMetadata.getMasterCardDrugPickupEncounterType().getEncounterTypeId(),
            hivMetadata.getReturnVisitDateConcept().getConceptId(),
            hivMetadata.getReturnVisitDateForArvDrugConcept().getConceptId(),
            hivMetadata.getArtDatePickup().getConceptId()));
}
```

**Comment by nthfloor** [comment]
Ah of course, sure will make that change :+1:

**Review by ynurmahomed — APPROVED** [review]

**Pull request merged**
