### PR TITLE
Mepts 358 changes in monthly report misau section e

### PR DESCRIPTION
**Pull request by ningosi**
Removal of unwanted sections within a report

### CODE REVIEW

**Comment by cfaife** [comment]
Hi @ningosi, please resolve the conflict here

**Comment by ningosi** [comment]
Looking into the conflict now

**Comment by ningosi** [comment]
conflicts ressolved

**Comment by cfaife** [comment]
Hi @ningosi  can please fix the  conflict here, I  believe it happened during the last merge into develop

**Comment by ningosi** [comment]
@cfaife this is also ready for review

**Review by psmatsinhe — APPROVED** [review]

**Pull request merged**
